[shell.session.power]
shutdown = "systemctl hibernate"

[[shell.session.actions]]
action = "lock"
command = ""
countdown_seconds = 0.0
enabled = true
glyph = ""
label = ""
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
command = ""
countdown_seconds = 0.0
enabled = true
glyph = ""
label = ""
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "lock_and_suspend"
command = ""
countdown_seconds = 0.0
enabled = true
glyph = ""
label = ""
shortcut = "3"
variant = "default"

[[shell.session.actions]]
action = "reboot"
command = ""
countdown_seconds = 0.0
enabled = true
glyph = ""
label = ""
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
command = "systemctl hibernate"
countdown_seconds = 0.0
enabled = true
glyph = ""
label = "关机"
shortcut = "5"
variant = "destructive"
