[config]

[templates]

[templates.starship]
input_path = "/home/dot/.dotfiles/home/dot/starship/starship.toml.template"
output_path = "/home/dot/.cache/starship.toml"

[templates.zellij]
input_path = "/home/dot/.dotfiles/home/dot/zellij/config.kdl.template"
output_path = "/home/dot/.cache/zellij.kdl"

[templates.neovim]
input_path = "/home/dot/.dotfiles/home/dot/nixvim/colors.lua.template"
output_path = "/home/dot/.cache/nvim_colors.lua"

[templates.antigravity]
input_path = "/home/dot/.dotfiles/home/dot/antigravity/theme.json.template"
output_path = "/home/dot/.cache/antigravity_theme.json"
