# ---
# Module: Chrome - Native Theme Injector
# Description: Injects Noctalia colors directly into Chrome's native Preferences
# Scope: Home Manager
# ---

{ pkgs, ... }:

let
  themeInjector = pkgs.writeShellScriptBin "chrome-theme-injector" ''
    set -eu
    ${pkgs.python3}/bin/python3 - <<'EOF'
import json
import os
import sys
import subprocess

colors_file = os.path.expanduser("~/.cache/chrome-noctalia-theme/colors.json")
prefs_path = os.path.expanduser("~/.config/google-chrome/Default/Preferences")
chromium_prefs_path = os.path.expanduser("~/.config/chromium/Default/Preferences")

if not os.path.exists(colors_file):
    sys.exit(0)

actual_prefs = None
if os.path.exists(prefs_path):
    actual_prefs = prefs_path
elif os.path.exists(chromium_prefs_path):
    actual_prefs = chromium_prefs_path
else:
    sys.exit(0)

# [Process Check]
chrome_was_running = False
try:
    check_chrome = subprocess.run(["pgrep", "-f", "chrome"], stdout=subprocess.DEVNULL)
    if check_chrome.returncode == 0:
        chrome_was_running = True
except:
    pass

# [Graceful Kill]
if chrome_was_running:
    subprocess.run(["pkill", "-f", "chrome"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    subprocess.run(["pkill", "-f", "chromium"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    # [Wait For Lock]
    import time
    for _ in range(100):
        if subprocess.run(["pgrep", "-f", "chrome"], stdout=subprocess.DEVNULL).returncode != 0:
            break
        time.sleep(0.01)

with open(colors_file, 'r', encoding='utf-8') as f:
    data = json.load(f)

hex_color = data.get("ntpLink", "#000000").strip().lstrip('#')
if len(hex_color) != 6:
    hex_color = "000000"

r = int(hex_color[0:2], 16)
g = int(hex_color[2:4], 16)
b = int(hex_color[4:6], 16)

argb = (255 << 24) | (r << 16) | (g << 8) | b
if argb >= 2**31:
    argb -= 2**32

with open(actual_prefs, 'r', encoding='utf-8') as f:
    prefs = json.load(f)

if "browser" not in prefs:
    prefs["browser"] = {}
if "theme" not in prefs["browser"]:
    prefs["browser"]["theme"] = {}

# [Theme Injection]
prefs["browser"]["theme"]["user_color2"] = argb
prefs["browser"]["theme"]["color"] = argb
prefs["browser"]["theme"]["color_scheme2"] = 0
prefs["browser"]["theme"]["color_variant2"] = 1
prefs["browser"]["theme"]["follows_system_colors"] = False

# [Cleanup Legacy Keys]
prefs.pop("autogenerated", None)
if "extensions" in prefs and "theme" in prefs["extensions"]:
    prefs["extensions"].pop("theme", None)

with open(actual_prefs, 'w', encoding='utf-8') as f:
    json.dump(prefs, f, separators=(',', ':'))

# [Restart]
if chrome_was_running:
    subprocess.Popen(["google-chrome-stable"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, stdin=subprocess.DEVNULL)
EOF
  '';
in {
  home.packages = [ themeInjector ];
}
